#! /bin/bash

source setup_variables.sh

CURRENT_DIR=$(pwd)
# printf "Change dir to petalinux & Source setting.sh?[y/N]: "
# read response

# if [ "$response" = "y" ]; then
cd "$PETALINUX_INSTALL_DIR"
source settings.sh
cd "$PETALINUX_PROJECT"

while true; do
	echo "-------------------------------------"
	echo "0 - Config PetaLinux"
	echo "1 - Build $PETALINUX_PROJECT"
	echo "2 - Package & boot on board"
	echo "3 - Reboot if bitfile program failed"
	echo "4 - Attach USB-IP Device"
	echo "5 - Remote Package and boot"
	echo "-------------------------------------"
	read response
	if [[ "$response" == *"0"* ]]; then
		printf "Configure Hardware?[y/N]: "
		read config_response
		if [ "$config_response" = "y" ]; then
			petalinux-config --oldconfig --get-hw-description="$ADI_HDL_PROJECT/projects/fft/zc702/fft_zc702.sdk"
		else
			petalinux-config
		fi
	fi
	if [[ "$response" == *"1"* ]]; then
		petalinux-build
	fi
	if [[ "$response" == *"2"* ]]; then
		petalinux-package --prebuilt --fpga images/linux/system.bit --force; petalinux-boot --jtag --prebuilt 3 -v; petalinux-boot --jtag --fpga --bitstream images/linux/system.bit
	fi
	if [[ "$response" == *"3"* ]]; then
		petalinux-boot --jtag --fpga --bitstream images/linux/system.bit
	fi
	if [[ "$response" == *"4"* ]]; then
		printf "Probe VHCI-HCD?[y/N]: "
		read usb_response
		if [ "$usb_response" = "y" ]; then
			sudo modprobe vhci-hcd
		fi
		/usr/lib/linux-tools/4.15.0-23-generic/usbip list -r 192.168.1.122
		sudo /usr/lib/linux-tools/4.15.0-23-generic/usbip attach -r 192.168.1.122 -b 1-5
	fi
	if [[ "$response" == *"5"* ]]; then
		petalinux-package --prebuilt --fpga images/linux/system.bit --force;
		cd "$CURRENT_DIR"
		cp Petalinux/zc702.tcl "$PETALINUX_INSTALL_DIR/$PETALINUX_PROJECT/"
		cd "$PETALINUX_INSTALL_DIR/$PETALINUX_PROJECT/"
		export PATH="$PATH:$XILINX_INSTALL_DIR/Vivado/$XILINX_VERSION/bin"
		xsdb -eval "source zc702.tcl"
	fi
done
# fi
