
proc getPresetInfo  {} {
	return [dict create  name PNA6  display_name  {PNA6}   description  {PNA6 board preset}  vlnv  xilinx.com:ip:processing_system7:5.5]
}

proc validate_preset {IPINST} {
  return true;
}

proc apply_preset {IPINST} {
    set c_family [[namespace parent]::get_project_property BOARD]
    set c_board [ lindex [split $c_family :] 1 ]
	if { $c_board != "pna6" } {
	  send_msg_id PS7-6 WARNING "The applied preset does not match with $c_board board preset. You may not get expected settings for $c_board board. The PNA6 preset is designed for PNA6 board." -verbose
	}
 
 [namespace parent]::Check_for_unbonded_pins $IPINST "PNA6"
 return [dict create \
  CONFIG.PCW_UIPARAM_DDR_ENABLE {0}  \
  CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE {0}  \
  CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_ECC {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_BL {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_PARTNO {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_SPEED_BIN {<Select>}  \
  CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {0}  \
  CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {0}  \
  CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {0}  \
  CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN {0}  \
  CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {0}  \
  CONFIG.PCW_DDR_PORT0_HPR_ENABLE {0}  \
  CONFIG.PCW_DDR_PORT1_HPR_ENABLE {0}  \
  CONFIG.PCW_DDR_PORT2_HPR_ENABLE {0}  \
  CONFIG.PCW_DDR_PORT3_HPR_ENABLE {0}  \
  CONFIG.PCW_DDR_HPRLPR_QUEUE_PARTITION {HPR(0)/LPR(32)}  \
  CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL {2}  \
  CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL {15}  \
  CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL {2}  \
  CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
  CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
  CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_0_SLEW {slow} \
  CONFIG.PCW_MIO_1_SLEW {slow} \
  CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_2_SLEW {slow} \
  CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_3_SLEW {slow} \
  CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_4_SLEW {slow} \
  CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_5_SLEW {slow} \
  CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_6_SLEW {slow} \
  CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_15_SLEW {slow} \
  CONFIG.PCW_MIO_16_SLEW {slow} \
  CONFIG.PCW_MIO_16_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_17_SLEW {slow} \
  CONFIG.PCW_MIO_17_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_18_SLEW {slow} \
  CONFIG.PCW_MIO_18_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_19_SLEW {slow} \
  CONFIG.PCW_MIO_19_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_20_SLEW {slow} \
  CONFIG.PCW_MIO_20_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_21_SLEW {slow} \
  CONFIG.PCW_MIO_21_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_22_SLEW {slow} \
  CONFIG.PCW_MIO_22_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_23_SLEW {slow} \
  CONFIG.PCW_MIO_23_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_24_SLEW {slow} \
  CONFIG.PCW_MIO_24_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_25_SLEW {slow} \
  CONFIG.PCW_MIO_25_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_26_SLEW {slow} \
  CONFIG.PCW_MIO_26_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_27_SLEW {slow} \
  CONFIG.PCW_MIO_27_IOTYPE {HSTL 1.8V} \
  CONFIG.PCW_MIO_28_SLEW {slow} \
  CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_29_SLEW {slow} \
  CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_30_SLEW {slow} \
  CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_31_SLEW {slow} \
  CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_32_SLEW {slow} \
  CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_33_SLEW {slow} \
  CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_34_SLEW {slow} \
  CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_35_SLEW {slow} \
  CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_36_SLEW {slow} \
  CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_37_SLEW {slow} \
  CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_38_SLEW {slow} \
  CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_39_SLEW {slow} \
  CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_40_SLEW {slow} \
  CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_41_SLEW {slow} \
  CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_42_SLEW {slow} \
  CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_43_SLEW {slow} \
  CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_44_SLEW {slow} \
  CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_45_SLEW {slow} \
  CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_2_PULLUP {disabled} \
  CONFIG.PCW_MIO_3_PULLUP {disabled} \
  CONFIG.PCW_MIO_4_PULLUP {disabled} \
  CONFIG.PCW_MIO_5_PULLUP {disabled} \
  CONFIG.PCW_MIO_6_PULLUP {disabled} \
  CONFIG.PCW_MIO_7_PULLUP {disabled} \
  CONFIG.PCW_MIO_8_PULLUP {disabled} \
  CONFIG.PCW_MIO_16_PULLUP {disabled} \
  CONFIG.PCW_MIO_17_PULLUP {disabled} \
  CONFIG.PCW_MIO_18_PULLUP {disabled} \
  CONFIG.PCW_MIO_19_PULLUP {disabled} \
  CONFIG.PCW_MIO_20_PULLUP {disabled} \
  CONFIG.PCW_MIO_21_PULLUP {disabled} \
  CONFIG.PCW_MIO_22_PULLUP {disabled} \
  CONFIG.PCW_MIO_23_PULLUP {disabled} \
  CONFIG.PCW_MIO_24_PULLUP {disabled} \
  CONFIG.PCW_MIO_25_PULLUP {disabled} \
  CONFIG.PCW_MIO_26_PULLUP {disabled} \
  CONFIG.PCW_MIO_27_PULLUP {disabled} \
  CONFIG.PCW_MIO_28_PULLUP {disabled} \
  CONFIG.PCW_MIO_29_PULLUP {disabled} \
  CONFIG.PCW_MIO_30_PULLUP {disabled} \
  CONFIG.PCW_MIO_31_PULLUP {disabled} \
  CONFIG.PCW_MIO_32_PULLUP {disabled} \
  CONFIG.PCW_MIO_33_PULLUP {disabled} \
  CONFIG.PCW_MIO_34_PULLUP {disabled} \
  CONFIG.PCW_MIO_35_PULLUP {disabled} \
  CONFIG.PCW_MIO_36_PULLUP {disabled} \
  CONFIG.PCW_MIO_37_PULLUP {disabled} \
  CONFIG.PCW_MIO_38_PULLUP {disabled} \
  CONFIG.PCW_MIO_39_PULLUP {disabled} \
  CONFIG.PCW_MIO_40_PULLUP {disabled} \
  CONFIG.PCW_MIO_41_PULLUP {disabled} \
  CONFIG.PCW_MIO_42_PULLUP {disabled} \
  CONFIG.PCW_MIO_43_PULLUP {disabled} \
  CONFIG.PCW_MIO_44_PULLUP {disabled} \
  CONFIG.PCW_MIO_45_PULLUP {disabled} \
  CONFIG.PCW_MIO_46_PULLUP {enabled} \
  CONFIG.PCW_MIO_47_PULLUP {enabled} \
  CONFIG.PCW_MIO_48_PULLUP {disabled} \
  CONFIG.PCW_MIO_49_PULLUP {disabled} \
  CONFIG.PCW_MIO_52_PULLUP {disabled} \
  CONFIG.PCW_MIO_53_PULLUP {disabled} \
  CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
  CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {666.666666} \
  CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {50} \
  CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 1.8V} \
  CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} ]
}

