#!/bin/sh
### BEGIN INIT INFO
# Provides:           load-config
# Required-Start      
# Required-Stop       
# Default-Start       5
# Default-Stop:       
# Short-Description:  PNA-Startup
### END INIT INFO

S=/mnt/sdcard
D=/etc/startup_script
C=pna-startup.sh

echo "PNA-Startup script by Dr.Bros started ..."

if [ "$1" != "start" ]; then
    exit 0
fi

# create directories/files
mkdir -p ${S}
mkdir -p ${D}

# mount the sd card
mount /dev/mmcblk0p1 ${S}

# Load ip file
if [ -f ${S}/pna_ip ]; then
    echo "Loading ip from SD"
    cp -v ${S}pna_ip /home/root/pna_ip
fi

if [ -f ${S}/${C} ]; then
    echo "Running pna-startup script"
    cp ${S}/${C} ${D}/${C}
    source ${D}/${C}
else
    echo "No startup script file found"
fi

#!/bin/sh

ifconfig eth0 down
ifconfig eth0 hw ether 12:13:14:15:16:17
ifconfig eth0 up
if [ -f /home/root/pna_ip ]; then
	PNA_IP=$(cat /etc/pna_ip)
    sleep 1
    ifconfig eth0 $PNA_IP
    
	WRITE_LN=$(grep -i -n 'iface eth0 inet dhcp' "/etc/network/interfaces" | awk -F : '{printf $1}')
	sed -i 's/iface eth0 inet dhcp/iface eth0 inet static/' "/etc/network/interfaces"
	WRITE_LN=$(($WRITE_LN+1))
	sed -i "$WRITE_LN"'i\ \ \ \ \ \ \ \ address '"$PNA_IP" "/etc/network/interfaces"
	WRITE_LN=$(($WRITE_LN+1))
	sed -i "$WRITE_LN"'i\ \ \ \ \ \ \ \ netmask 255.255.255.0' "/etc/network/interfaces"
	WRITE_LN=$(($WRITE_LN+1))
	sed -i "$WRITE_LN"'i\ \ \ \ \ \ \ \ gateway 192.168.1.1' "/etc/network/interfaces"
fi

umount ${S}

# set hostname again, in case it changed
/etc/init.d/hostname.sh

exit 0
