#!/bin/sh
### BEGIN INIT INFO
# Provides:           load-config
# Required-Start      
# Required-Stop       
# Default-Start       5
# Default-Stop:       
# Short-Description:  PNA-Startup
### END INIT INFO

S=/mnt/sdcard
D=/etc/startup_script
C=pna-startup.sh

echo "pna-startup: Dr.Bros App started ..."

if [ "$1" != "start" ]; then
    exit 0
fi

# create directories/files
mkdir -p ${S}
mkdir -p ${D}

# mount the sd card
mount /dev/mmcblk0p1 ${S}

# Load board name file
mkdir /etc/pna_iio
printf e310 > /etc/pna_iio/board_name

# Load ip file
if [ -f ${S}/pna_ip ]; then
    echo "Loading ip from SD"
    cp -v ${S}/pna_ip /etc/pna_iio/pna_ip
fi

if [ -f ${S}/${C} ]; then
    echo "Running pna-startup script"
    cp ${S}/${C} ${D}/${C}
    source ${D}/${C}
else
    echo "No startup script file found"
fi

#!/bin/sh

ifconfig eth0 down
ifconfig eth0 hw ether 12:13:14:15:16:18
ifconfig eth0 up

if [ -f /etc/pna_iio/pna_ip ]; then
	echo "pna-startup: applying pna_ip ..."
	PNA_IP=$(cat /etc/pna_iio/pna_ip)
    sleep 1
    ifconfig eth0 $PNA_IP
fi

if [ -f ${S}/fft_zc702_linux.elf ]; then
	echo "pna-startup: adding elf file ..."
	cp -v "${S}/fft_zc702_linux.elf" "/home/root/fft_zc702_linux.elf"
fi

umount ${S}

# set hostname again, in case it changed
/etc/init.d/hostname.sh

exit 0
